import type { Persona } from "@/lib/types";

/**
 * 36 demo personas across all tiers per PRD §10.1
 * Avatar color classes use Tailwind bg colours.
 */
export const PERSONAS: Persona[] = [
  // T0 — CMD
  {
    id: "cmd-arjun",
    name: "Arjun Mehta",
    role: "CMD — Chairman & Managing Director",
    tier: 0,
    accountType: "employee",
    department: "Board",
    avatar: "AM",
    color: "bg-navy-800",
    description: "Portfolio overview, risk & audit summaries. Read-only access across all units.",
  },
  // T1 — Directors
  {
    id: "dir-finance-priya",
    name: "Priya Krishnan",
    role: "Director — Finance",
    tier: 1,
    accountType: "employee",
    department: "Finance",
    avatar: "PK",
    color: "bg-blue-600",
    description: "Oversees financial operations across all units. Approves cross-department finance access.",
  },
  {
    id: "dir-hr-ravi",
    name: "Ravi Shankar",
    role: "Director — Human Resources",
    tier: 1,
    accountType: "employee",
    department: "Human Resources",
    avatar: "RS",
    color: "bg-blue-600",
    description: "HR policy, skills certification, credential issuance authority.",
  },
  {
    id: "dir-rd-neha",
    name: "Neha Gupta",
    role: "Director — R&D",
    tier: 1,
    accountType: "employee",
    department: "R&D",
    avatar: "NG",
    color: "bg-blue-600",
    description: "Research and development authority. Oversees design validation and technical release.",
  },
  {
    id: "dir-ops-suresh",
    name: "Suresh Pillai",
    role: "Director — Operations",
    tier: 1,
    accountType: "employee",
    department: "Operations",
    avatar: "SP",
    color: "bg-blue-600",
    description: "Production, logistics, and supply chain authority.",
  },
  // T2 — Unit Head / CISO / CVO
  {
    id: "ciso-rohan",
    name: "Rohan Sharma",
    role: "CISO / ERP Administrator",
    tier: 2,
    accountType: "erp_admin",
    department: "IT & Security",
    avatar: "RS",
    color: "bg-saffron-500",
    description: "Full platform authority. Manages users, roles, audit data, and security posture.",
  },
  {
    id: "cvo-deepa",
    name: "Deepa Iyer",
    role: "Chief Vigilance Officer",
    tier: 2,
    accountType: "employee",
    department: "Vigilance",
    avatar: "DI",
    color: "bg-amber-600",
    description: "Read-all access + alert-raising. Cannot modify any records. Oversight watchdog.",
  },
  {
    id: "uh-bangalore",
    name: "Vikram Nair",
    role: "Unit Head (GM) — Bangalore",
    tier: 2,
    accountType: "employee",
    department: "Unit Management",
    avatar: "VN",
    color: "bg-navy-800",
    description: "General Manager of Bangalore unit. Approves unit-wide decisions.",
  },
  // T3 — Department Heads
  {
    id: "dh-procurement-kavya",
    name: "Kavya Rao",
    role: "Dept Head — Procurement (DGM)",
    tier: 3,
    accountType: "employee",
    department: "Procurement",
    avatar: "KR",
    color: "bg-ink-600",
    description: "First approver for procurement data access. Manages vendor relationships.",
  },
  {
    id: "dh-finance-arun",
    name: "Arun Kumar",
    role: "Dept Head — Finance (DGM)",
    tier: 3,
    accountType: "employee",
    department: "Finance",
    avatar: "AK",
    color: "bg-ink-600",
    description: "First approver for financial records and cost reports.",
  },
  {
    id: "dh-production-meena",
    name: "Meena Reddy",
    role: "Dept Head — Production (DGM)",
    tier: 3,
    accountType: "employee",
    department: "Production",
    avatar: "MR",
    color: "bg-ink-600",
    description: "Oversees assembly readiness, BOM management, and work orders.",
  },
  {
    id: "dh-quality-sanjay",
    name: "Sanjay Bose",
    role: "Dept Head — Quality (DGM)",
    tier: 3,
    accountType: "employee",
    department: "Quality",
    avatar: "SB",
    color: "bg-ink-600",
    description: "Quality inspections, NCR closure, acceptance evidence authority.",
  },
  {
    id: "dh-rd-anita",
    name: "Anita Patel",
    role: "Dept Head — R&D (DGM)",
    tier: 3,
    accountType: "employee",
    department: "R&D",
    avatar: "AP",
    color: "bg-ink-600",
    description: "Design validation, technical release, and design asset minting authority.",
  },
  {
    id: "dh-compliance-ritu",
    name: "Ritu Verma",
    role: "Dept Head — Compliance (DGM)",
    tier: 3,
    accountType: "employee",
    department: "Compliance",
    avatar: "RV",
    color: "bg-ink-600",
    description: "Compliance checks, exceptions register, regulatory evidence management.",
  },
  {
    id: "dh-security-amit",
    name: "Amit Singh",
    role: "Asset Custody Security Approver",
    tier: 3,
    accountType: "employee",
    department: "Security",
    avatar: "AS",
    color: "bg-red-600",
    description: "Two-person approval queue for Secret(demo) assets. Custody transfer authority.",
  },
  // T4 — Officers (2 per role, 13 roles)
  {
    id: "proc-aarav",
    name: "Aarav Joshi",
    role: "Procurement Officer",
    tier: 4,
    accountType: "employee",
    department: "Procurement",
    avatar: "AJ",
    color: "bg-green-600",
    description: "Manages RFQs, supplier evaluations, and purchase orders.",
  },
  {
    id: "proc-divya",
    name: "Divya Menon",
    role: "Senior Procurement Officer",
    tier: 4,
    accountType: "employee",
    department: "Procurement",
    avatar: "DM",
    color: "bg-green-600",
    description: "Handles international vendor procurement and PO tracking.",
  },
  {
    id: "fin-rahul",
    name: "Rahul Choudhary",
    role: "Finance Officer",
    tier: 4,
    accountType: "employee",
    department: "Finance",
    avatar: "RC",
    color: "bg-green-600",
    description: "Invoice review, cost assurance, and budget variance tracking.",
  },
  {
    id: "prod-sunita",
    name: "Sunita Kumari",
    role: "Production Manager",
    tier: 4,
    accountType: "employee",
    department: "Production",
    avatar: "SK",
    color: "bg-green-600",
    description: "Assembly readiness, BOM management, and work order scheduling.",
  },
  {
    id: "qc-mohan",
    name: "Mohan Das",
    role: "Quality Officer",
    tier: 4,
    accountType: "employee",
    department: "Quality",
    avatar: "MD",
    color: "bg-green-600",
    description: "Quality inspections, NCR tracking, and acceptance evidence.",
  },
  {
    id: "rd-preethi",
    name: "Preethi Nambiar",
    role: "R&D / Engineering Officer",
    tier: 4,
    accountType: "employee",
    department: "R&D",
    avatar: "PN",
    color: "bg-green-600",
    description: "Design validation, technical release, and NFT minting for design assets.",
  },
  {
    id: "rd-kiran",
    name: "Kiran Hegde",
    role: "Senior R&D Engineer",
    tier: 4,
    accountType: "employee",
    department: "R&D",
    avatar: "KH",
    color: "bg-green-600",
    description: "Firmware development, document versioning, and design asset custody.",
  },
  {
    id: "log-vijay",
    name: "Vijay Subramanian",
    role: "Logistics Officer",
    tier: 4,
    accountType: "employee",
    department: "Logistics",
    avatar: "VS",
    color: "bg-green-600",
    description: "Dispatch planning, shipment tracking, and inventory movement.",
  },
  {
    id: "hr-lakshmi",
    name: "Lakshmi Krishnaswamy",
    role: "HR Officer",
    tier: 4,
    accountType: "employee",
    department: "Human Resources",
    avatar: "LK",
    color: "bg-green-600",
    description: "Skills certification, competency matrix, and verifiable credential issuance.",
  },
  {
    id: "audit-prakash",
    name: "Prakash Iyer",
    role: "Internal Auditor",
    tier: 4,
    accountType: "employee",
    department: "Internal Audit",
    avatar: "PI",
    color: "bg-green-600",
    description: "Control testing, audit sampling. Read-only across departments, cannot modify.",
  },
  // T5 — Trainees
  {
    id: "trainee-ananya",
    name: "Ananya Shetty",
    role: "Graduate Trainee",
    tier: 5,
    accountType: "employee",
    department: "R&D",
    avatar: "AT",
    color: "bg-ink-400",
    description: "View-only on assigned items. No downloads of Confidential content.",
  },
  {
    id: "trainee-rohit",
    name: "Rohit Bansal",
    role: "Technician Trainee",
    tier: 5,
    accountType: "employee",
    department: "Production",
    avatar: "RB",
    color: "bg-ink-400",
    description: "Assigned production tasks only. Read-only access.",
  },
  // EXT-V — Vendors
  {
    id: "vendor-novatech",
    name: "NovaTech Components Pvt. Ltd.",
    role: "Vendor — Electronics Supplier",
    tier: 9,
    accountType: "vendor",
    department: "External",
    avatar: "NT",
    color: "bg-blue-600",
    description: "Upload delivery evidence, view approved POs. Restricted to own orders.",
  },
  {
    id: "vendor-shieldtech",
    name: "ShieldTech Solutions",
    role: "Vendor — Defense Components",
    tier: 9,
    accountType: "vendor",
    department: "External",
    avatar: "ST",
    color: "bg-blue-600",
    description: "Specialized defense electronics components supplier.",
  },
  {
    id: "vendor-precisionworks",
    name: "PrecisionWorks Engineering",
    role: "Vendor — Precision Manufacturing",
    tier: 9,
    accountType: "vendor",
    department: "External",
    avatar: "PW",
    color: "bg-blue-600",
    description: "High-precision mechanical components for radar and communications systems.",
  },
  // EXT-C — Customers
  {
    id: "customer-defence",
    name: "Defence Systems Demo Client",
    role: "Customer — Government Defence",
    tier: 9,
    accountType: "customer",
    department: "External",
    avatar: "DS",
    color: "bg-saffron-500",
    description: "View approved deliveries, sign acceptance certificates digitally.",
  },
  {
    id: "customer-navy",
    name: "Naval Research Demo Client",
    role: "Customer — Naval Systems",
    tier: 9,
    accountType: "customer",
    department: "External",
    avatar: "NR",
    color: "bg-saffron-500",
    description: "Milestone tracking and acceptance for naval communications systems.",
  },
];

/** Quick lookup by ID */
export const PERSONA_MAP = new Map(PERSONAS.map((p) => [p.id, p]));

/** Group personas by account type */
export const EMPLOYEE_PERSONAS = PERSONAS.filter(
  (p) => p.accountType === "employee"
);
export const ADMIN_PERSONAS = PERSONAS.filter(
  (p) => p.accountType === "erp_admin"
);
export const VENDOR_PERSONAS = PERSONAS.filter(
  (p) => p.accountType === "vendor"
);
export const CUSTOMER_PERSONAS = PERSONAS.filter(
  (p) => p.accountType === "customer"
);

/** Featured personas for the landing page quick-login grid */
export const FEATURED_PERSONAS: Persona[] = [
  PERSONAS.find((p) => p.id === "ciso-rohan")!,
  PERSONAS.find((p) => p.id === "proc-aarav")!,
  PERSONAS.find((p) => p.id === "dh-procurement-kavya")!,
  PERSONAS.find((p) => p.id === "cvo-deepa")!,
  PERSONAS.find((p) => p.id === "rd-preethi")!,
  PERSONAS.find((p) => p.id === "vendor-novatech")!,
  PERSONAS.find((p) => p.id === "customer-defence")!,
  PERSONAS.find((p) => p.id === "cmd-arjun")!,
];
